#!/bin/bash

mkdir IS-03_Maxym_Pishchuk
cd IS-03_Maxym_Pishchuk
wget -O site_text.txt  https://raw.githubusercontent.com/xpams/UIView-Blur/master/README.md 
wget --output-document=important.jpeg https://raw.githubusercontent.com/KurtC0bain/kali/master/Studio_Project.jpeg?token=ALQUMQEUILVIWSCBEQX5PTS75OUXS
echo "File was successfully downloaded!"
echo " "
echo " "
for((q = 0; q < 35; q++))
do
echo -n "#"
done
echo " "
echo -n "The number of lines (site_txt.txt): "
cat site_text.txt | wc -l
for((a = 0; a < 35; a++))
do 
echo -n "#"
done
for ((b = 0; b < 5; b++))
do
echo " "
done
echo "!CHECK THE importnat.jpeg IN MY FOLDER!"
for ((c = 0; c < 5; c++))
do
echo "" 
done

